### ISSUE TITLE
tarmak#3 missing X

### ISSUE THREAD

**Issue by algj** [azmr/tarmak-cli#1]
```
q w f p g j L U y ;
 a r s t d h n e I o
  z c v b k m
```

should be

```
q w f p g j L U y ;
 a r s t d h n e I o
  z x c v b k m
```

**Comment by DreymaR** [comment]
Hmmm... That mistake is in the full Colemak, not in Tarmak3. It's in the documentation a couple of places:
https://github.com/azmr/tarmak-cli/blob/master/steps.txt
https://github.com/azmr/tarmak-cli/blob/master/README.md

I don't think the actual functionality is affected in any way.

**Comment by azmr** [comment]
Thanks for pointing this out and thanks to @DreymaR for noting the locations.
As mentioned, this is just a typo in the documentation and shouldn't have had any effect on actual layouts.
